EBIvariation/eva-tasks

tasks/eva_2124/correct_contig_for_study.py, tasks/eva_2130/remove_duplicates_in_study.py
Script to remove duplicated entries. It come on top of PR https://github.com/EBIvariation/eva-tasks/pull/9
=> EVA-2130  - remove duplicates

tasks/eva_2150/__init__.py, tasks/eva_2150/collect_assembly_report_genbank_contigs.py, tasks/eva_2150/collect_mongo_genbank_contigs.py, tasks/eva_2150/requirements.txt
See [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2150?focusedCommentId=335906&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-335906) and [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2150?focusedCommentId=336047&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-336047) for usage.
=> EVA-2150 - Detect extra contigs in MongoDB that do not show up in the assembly report

tasks/EVA_2149/copy_database.py
Add script to copy one database to another within the same server
=> EVA-2147 - script to copy database withing the same server

tasks/eva_2124/correct_contig_for_study_rs.py
This is basically a copy paste from correct_contig_for_study.py.
If we plan to keep using these scripts we should refactor them.
=> EVA-2131 EVA-2124 add correct_contig_for_study_rs.py

tasks/eva_2245/check_subsnp_assumptions.py
See commentary [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2245?focusedCommentId=344459&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-344459)
=> EVA-2245 - Strategy to extract SubSNPs from human release JSON

tasks/eva_2194/count_rs_for_release2.sh, tasks/eva_2194/count_rs_for_release2_for_txt.sh, tasks/eva_2194/count_rs_for_release2_unmapped.sh
Three scripts to count the rs is specific file type in a release by species
=> EVA-2194 - Count RS id per species

tasks/eva_2146/merge_prjeb25004_redundant_ssids.groovy, tasks/eva_2146/update_prjeb25004_ss_contigs.groovy
Commentary and usage [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2146?focusedCommentId=345491&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-345491) and [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2146?focusedCommentId=345626&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-345626)
=> EVA-2146 - Merge redundant SS IDs in PRJEB25004

tasks/eva_2301/check_bowtie_metrics.Rmd, tasks/eva_2301/find_FP_variants.py, tasks/eva_2301/tests/test_find_FP_variants.py
Script to extract reads from bam files based on Hap.py results
R markdown notebook comparing the most useful metrics in the alignment records
=> EVA-2301 - Extract metrics from alignment files

tasks/eva_2323/dump_studies_json.py, tasks/eva_2323/requirements.txt
Simple script that translate the content of the EVAPRO database to JSON or get the same data from the all studies endpoint
=> EVA-2323 - Script to dump basic json corresponding to the studies found in EVA

tasks/eva_2406/count_studies.sh, tasks/eva_2406/gather_release_species.py, tasks/eva_2406/load_accession.py, tasks/eva_2406/requirements.txt
Suite of script to be used to gather information about the assemblies to release
detail of usage available in [this comment](https://www.ebi.ac.uk/panda/jira/browse/EVA-2406?focusedCommentId=359193&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-359193)
=> EVA-2406 - Scripts to gather information about assemblies to remap 

tasks/eva_2469/collect_assembly_report_genbank_contigs.py, tasks/eva_2469/get_possible_assemblies_for_contigs.py, tasks/eva_2469/requirements.txt
Usage and purpose [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2469?focusedCommentId=362944&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-362944) and [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-2469?focusedCommentId=363066&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-363066)
=> EVA-2469 - Assess out-of-asm-rpt contigs

tasks/eva_2706/detect_discordant_cluster_variant.py, tasks/eva_2706/detect_discordant_cluster_variant_from_split_merge_operations.py, tasks/eva_2706/detect_discordant_cluster_variant_from_split_merge_operations_and_resolve_them.py
Script to detect clustered variant discordant with their submitted variants
=> EVA-2706 - Discordant clustered variants 

tasks/eva_2778/categorise_missing_rs.py, tasks/eva_2778/check_rs_exist.py, tasks/eva_2778/test/test_check_rs_exist.py
New script to detect the clustered variants references in the submitted variant collection but not present in the clustered variant collection
=> EVA-2778 - Detect missing RS

tasks/eva_2779/correct_assembly_error_in_rat.py
Catch duplicated key error and avoid failure when they occur
=> EVA-2779 - Correct assembly in accessioning database for Rattus norvegicus

tasks/eva_2901/check_submitted_variant_flanks.py
Script to compare multiple instance of the same variant across assemblies.
=> EVA-2901 - Compare multiple submitted variants through alignment

tasks/eva_3004/eva3004/pom.xml, tasks/eva_3004/eva3004/src/uk/ac/ebi/eva/eva3004/EVACursor.groovy, tasks/eva_3004/eva3004/src/uk/ac/ebi/eva/eva3004/eva2959_shelve_discordant_rs_not_considered.groovy, tasks/eva_3004/eva3004/src/uk/ac/ebi/eva/eva3004/eva3001_create_svoe_entries_for_rs_merges.groovy, tasks/eva_3004/eva3004/src/uk/ac/ebi/eva/eva3004/eva3004_remove_ss_from_main_collections.groovy, tasks/eva_3004/eva3004/src/uk/ac/ebi/eva/eva3004/qc_eva2959_prod.groovy
* [Script to remove shelved SS from main collections](https://github.com/EBIvariation/eva-tasks/compare/master...sundarvenkata-EBI:eva-tasks:eva3004/shelve_problematic_ss_rs?expand=1#diff-1d7e06c947e9943df9585f956433078de2d856d64ea7d223cd204054aac9529f)
* [Script](https://github.com/EBIvariation/eva-tasks/compare/master...sundarvenkata-EBI:eva-tasks:eva3004/shelve_problematic_ss_rs?expand=1#diff-4156609dd43771a73fca03552635e641a69241d832672290099f1da3cdb7147c) to create submitted ops corresponding to clustered ops created in EVA-2850
* A few updates to counts after some scripts were re-run after RS map-weight propagation to SS
=> EVA-3004 - Remove shelved SS from main collections

tasks/eva_3027/eva3027/logback.xml, tasks/eva_3027/eva3027/pom.xml, tasks/eva_3027/eva3027/src/uk/ac/ebi/eva/eva3027/EVACursor.groovy, tasks/eva_3027/eva3027/src/uk/ac/ebi/eva/eva3027/EVADatabaseEnvironment.groovy, tasks/eva_3027/eva3027/src/uk/ac/ebi/eva/eva3027/EVALoggingUtils.groovy, tasks/eva_3027/eva3027/src/uk/ac/ebi/eva/eva3027/eva3027_restore_shelved_ss.groovy
All the scripts other than [eva3027_restore_shelved_ss.groovy](https://github.com/EBIvariation/eva-tasks/compare/master...sundarvenkata-EBI:eva-tasks:fix/eva3027_restore_shelved_ss?expand=1#diff-6ca5ff95678264f686dfd3fb43e7620c82aa03e5c4a542a7b2088a5fe46e8d76) were copied from [eva_3004](https://github.com/EBIvariation/eva-tasks/pull/89). So, that is the only script to be reviewed.
=> EVA-3027 - Script to restore shelved SS

tasks/eva_3085/eva3085/logback.xml, tasks/eva_3085/eva3085/pom.xml, tasks/eva_3085/eva3085/src/uk/ac/ebi/eva/eva3085/EVACursor.groovy, tasks/eva_3085/eva3085/src/uk/ac/ebi/eva/eva3085/EVADatabaseEnvironment.groovy, tasks/eva_3085/eva3085/src/uk/ac/ebi/eva/eva3085/EVALoggingUtils.groovy, tasks/eva_3085/eva3085/src/uk/ac/ebi/eva/eva3085/eva3085_discard.groovy
Pending creation of the Groovy library, I copied `EVADatabaseEnvironment` etc. from [EVA-3027](https://github.com/EBIvariation/eva-tasks/tree/master/tasks/eva_3027/eva3027).  The only file you need to review is `eva3085_discard.groovy`.
=> EVA-3085 - Script to discard SVE/CVE

tasks/eva_3059/.gitignore, tasks/eva_3059/logback.xml, tasks/eva_3059/pom.xml, tasks/eva_3059/src/main/groovy/eva3059/deprecate_submitted_variants_by_accession.groovy
Followed the setup instructions [here](https://www.ebi.ac.uk/seqdb/confluence/display/VAR/Groovy+project+creation+steps)
=> EVA-3059 - Groovy script to deprecate variant by accession

tasks/eva_3145/logback.xml, tasks/eva_3145/pom.xml, tasks/eva_3145/src/main/groovy/eva3145/AsmMatchMetrics.groovy, tasks/eva_3145/src/main/groovy/eva3145/eva3145_analysis.groovy
Usage [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-3145?focusedId=418635&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-418635)
=> EVA-3145 - Analyze stats for variants with allelesMatch false

tasks/eva_3158/Dockerfile, tasks/eva_3158/config_file.yml
This docker file show what is needed to run submission automation.
=> EVA-3158 - Docker file wrapping around eva-submission validation

tasks/eva_3196/logback.xml, tasks/eva_3196/pom.xml, tasks/eva_3196/src/main/groovy/eva3196/eva3196_deprecate_orphaned_rs_by_type.groovy, tasks/eva_3196/src/main/groovy/eva3196/eva3196_qc_deprecate_orphaned_rs_by_type.groovy
Usage [here](https://www.ebi.ac.uk/panda/jira/browse/EVA-3196?focusedId=424657&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-424657)
=> EVA-3196 - Deprecate orphaned RS by type

tasks/eva_3229/gather_counts_from_count_service.py
Refer to spreadsheet [here](https://docs.google.com/spreadsheets/d/1UT-zUS_hePjxSUwfkJysXjkZC5iFWdXQQIBandqQs-I/edit?usp=sharing)
=> EVA-3229 Clustering counts strategy

tasks/eva_3314/logback.xml, tasks/eva_3314/pom.xml, tasks/eva_3314/src/main/groovy/eva3314/eva3314_deprecate_tax_469796_remapping.groovy
Differences from EVA-3309 PR [here](https://www.diffchecker.com/4tHRT9zB/)
=> EVA-3314 - Undo remapping of Ovis orientalis

tasks/eva_3649/findStudiesForImportAccession.py
As part of this PR only [tasks/eva_3649/findStudiesForImportAccession.py](https://github.com/EBIvariation/eva-tasks/compare/master...nitin-ebi:eva-tasks:find_studies_for_import_accession?expand=1#diff-8c5fe2ccf98e0cb39c97438df57145f5733253b138a59c975df7bb667ae74ea1) needs to be reviewed.
Other changes are from [EVA2038](https://www.ebi.ac.uk/panda/jira/browse/EVA-2038) for which there is already a separate PR waiting to be reviewed and merged
=> EVA-3649 Find studies for import accession

tasks/eva_9999/vcf_validator_donwloads.py
Very simple script I used to provide to Thomas the number of time vcf-validator was downloaded
=> Script to count the number of download from validator

tasks/eva_3779/delete_remapped_variants.py, tasks/eva_3779/ingest_remapped_vcf.nf
Scripts to delete variants and load them back in the accessioning warehouse
=> EVA-3779 - New script to delete variants that were remapped

tasks/eva_2326/src/main/groovy/eva2326/ContigRenamingProcessor.groovy, tasks/eva_2326/src/main/groovy/eva2326/update_contig_name.groovy, tasks/eva_2326/src/test/groovy/eva2326/UpdateContigNameApplicationTest.groovy
1. Updated some stream functions that were giving errors when collecting values in map (when the value was null)
2. Updated code to update the chromosome field along with chromosome ID in collection annotations_2_0 whenever the corresponding variant was updated
=> EVA-3824 minor updates to update contig naming script
